# Generated by Django 5.2.14 on 2026-05-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('VOLEY', 'Vóley'), ('FUTBOL', 'Fútbol 5'), ('BASQUET', 'Básquet'), ('PADEL', 'Pádel')], max_length=20)),
            ],
        ),
    ]
