# Generated by Django 5.2.14 on 2026-06-15 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turnos', '0008_alter_clase_costo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_anotacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_notificacion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('notificado', 'Notificado'), ('expirado', 'Expirado')], default='pendiente', max_length=20)),
                ('clase_programada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_espera', to='turnos.claseprogramada')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_espera', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha_anotacion'],
                'unique_together': {('user', 'clase_programada')},
            },
        ),
    ]
