# Generated by Django 5.0.14 on 2026-07-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_espera', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaespera',
            name='fecha_notificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
