# Generated by Django 5.2.14 on 2026-05-27 05:47

import socios.models
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', socios.models.SocioManager()),
            ],
        ),
    ]
