# Generated by Django 5.2.14 on 2026-06-09 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('socio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credito', to='socios.socio')),
            ],
        ),
    ]
