# Generated by Django 5.2.14 on 2026-06-28 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_alter_actividad_nombre'),
        ('socios', '0002_credito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('usado', models.BooleanField(default=False)),
                ('fecha_uso', models.DateTimeField(blank=True, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vales', to='actividades.actividad')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vales', to='socios.socio')),
            ],
            options={
                'verbose_name': 'Vale',
                'verbose_name_plural': 'Vales',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.DeleteModel(
            name='Credito',
        ),
    ]
