# Generated by Django 5.2.14 on 2026-05-17 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='espacio',
            field=models.CharField(choices=[('CANCHA_COMBINADA', 'Cancha Combinada'), ('CANCHA_PADDLE_1', 'Cancha Paddle 1'), ('CANCHA_PADDLE_2', 'Cancha Paddle 2'), ('CANCHA_FUTBOL_1', 'Cancha Fútbol 1'), ('CANCHA_FUTBOL_2', 'Cancha Fútbol 2')], default='CANCHA_FUTBOL_2', max_length=20),
            preserve_default=False,
        ),
    ]
