# Generated by Django 5.2.14 on 2026-05-17 02:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_clase_espacio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='clase',
            name='cupo_maximo',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
