# Generated by Django 5.2.14 on 2026-05-18 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_alter_clase_costo_alter_clase_cupo_maximo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseProgramada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.clase')),
            ],
            options={
                'unique_together': {('clase', 'fecha')},
            },
        ),
    ]
