# Generated by Django 5.2.14 on 2026-05-18 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0004_claseprogramada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claseprogramada',
            options={'ordering': ['fecha', 'clase__hora_inicio']},
        ),
    ]
