# Generated by Django 5.2.14 on 2026-05-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0005_alter_claseprogramada_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
