# Generated by Django 5.2.14 on 2026-05-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0006_turno_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
