# Generated by Django 5.2.14 on 2026-05-29 08:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0007_clase_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
