# Generated by Django 5.2.14 on 2026-05-18 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turnos', '0004_claseprogramada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=20)),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True)),
                ('metodo_asistencia', models.CharField(blank=True, choices=[('MANUAL', 'Manual'), ('QR', 'Código QR')], default=None, max_length=20, null=True)),
                ('clase_programada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.claseprogramada')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'unique_together': {('user', 'clase_programada')},
            },
        ),
    ]
