# Generated by Django 5.2.14 on 2026-05-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('CANCELADA', 'Cancelada'), ('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente')], default='ACTIVA', max_length=20),
        ),
    ]
