# Generated by Django 5.2.14 on 2026-05-18 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_reserva_unique_together_alter_reserva_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-fecha_reserva'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
    ]
