# Generated by Django 5.2.14 on 2026-05-18 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_alter_reserva_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-fecha_reserva', 'estado'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
    ]
