# Generated by Django 5.2.14 on 2026-05-18 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_alter_reserva_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['estado', '-fecha_reserva'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
    ]
