# Generated by Django 5.2.14 on 2026-05-22 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_alter_reserva_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='asistio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserva',
            name='pago_confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
