# Generated by Django 5.2.14 on 2026-05-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_reserva_metodo_pago_alter_reserva_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='sena_devuelta',
            field=models.BooleanField(default=False),
        ),
    ]
