# Generated by Django 5.2.14 on 2026-05-27 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_alter_reserva_user'),
        ('reservas', '0009_reserva_sena_devuelta'),
    ]

    operations = [
    ]
