# Generated by Django 5.2.14 on 2026-05-27 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0011_inscripcion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together=set(),
        ),
    ]
