# Generated by Django 5.2.14 on 2026-06-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0012_alter_inscripcion_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='mp_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='mp_preference_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('CANCELADA', 'Cancelada'), ('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente'), ('PENDIENTE_PAGO', 'Pendiente de Pago')], default='ACTIVA', max_length=20),
        ),
    ]
