# Generated by Django 5.2.14 on 2026-06-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0012_alter_inscripcion_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='pago_total_confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
