# Generated by Django 5.2.14 on 2026-06-12 21:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0012_alter_inscripcion_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='qr_token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
