# Generated by Django 5.2.14 on 2026-06-12 21:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0013_reserva_qr_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='qr_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
