# Generated by Django 5.2.15 on 2026-06-29 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0013_reserva_mp_payment_id_reserva_mp_preference_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('INICIADA', 'Iniciada (En proceso de pago)'), ('ACTIVA', 'Activa (Pagado 100%)'), ('CANCELADA', 'Cancelada'), ('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente'), ('PENDIENTE_PAGO', 'Pendiente de Pago (Señada)')], default='INICIADA', max_length=20),
        ),
    ]
