# Generated by Django 5.2.15 on 2026-06-30 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0013_reserva_pago_total_confirmado'),
        ('reservas', '0014_alter_reserva_estado'),
    ]

    operations = [
    ]
