# Generated by Django 5.2.15 on 2026-06-30 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0015_merge_20260630_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={},
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='pago_total_confirmado',
        ),
    ]
