# Generated by Django 5.2.15 on 2026-06-30 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0014_alter_reserva_estado'),
        ('reservas', '0015_alter_reserva_estado'),
    ]

    operations = [
    ]
