# Generated by Django 5.2.15 on 2026-06-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0016_remove_pago_total_confirmado'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='mp_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='mp_preference_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='estado',
            field=models.CharField(choices=[('INICIADA', 'Iniciada (En proceso de pago)'), ('ACTIVA', 'Activa'), ('DE_BAJA', 'De Baja')], default='ACTIVA', max_length=20),
        ),
    ]
