# Generated by Django 5.2.15 on 2026-06-30 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0016_merge_20260630_0051'),
        ('reservas', '0017_inscripcion_mp_payment_id_and_more'),
    ]

    operations = [
    ]
