<<<<<<< HEAD
# Generated by Django 5.2.14 on 2026-07-07 20:54
=======
# Generated by Django 5.0.14 on 2026-07-02 02:38
>>>>>>> listaespera

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0018_merge_20260630_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('INICIADA', 'Iniciada (En proceso de pago)'), ('ACTIVA', 'Activa (Pagado 100%)'), ('CANCELADA', 'Cancelada'), ('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente'), ('PENDIENTE_PAGO', 'Pendiente de Pago (Señada)')], default='INICIADA', max_length=20),
        ),
    ]
