# Generated by Django 5.0.14 on 2026-07-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0019_alter_reserva_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('INICIADA', 'Iniciada'), ('ACTIVA', 'Activa'), ('CANCELADA', 'Cancelada'), ('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente'), ('PENDIENTE_PAGO', 'Señada')], default='INICIADA', max_length=20),
        ),
    ]
